PKUHPC/CraneSched-FrontEnd

internal/cbatch/cbatch.go, protos/Crane.proto
(cherry picked from commit c4f424da013342b6d9ab83c555ee2956ccfe4d38)
=> refactor cbatch --repeat

internal/cacct/CmdArgParser.go, internal/cacct/cacct.go, internal/cacctmgr/CmdArgParser.go, internal/cacctmgr/cacctmgr.go, internal/cqueue/CmdArgParser.go
1. cacct/cacctmgr格式和cqueue统一
2. cacct/cacctmgr/cqueue的help详细使用说明
=> Format description

cmd/calloc/calloc.go, internal/cacct/CmdArgParser.go, internal/cacct/cacct.go, internal/cacctmgr/CmdArgParser.go, internal/cacctmgr/cacctmgr.go, internal/calloc/CmdArgParser.go, internal/cbatch/CmdArgParser.go, internal/cbatch/cbatch.go, internal/ccancel/CmdArgParser.go, internal/ccancel/ccancel.go, internal/ccontrol/CmdArgParser.go, internal/ccontrol/ccontrol.go, internal/cfored/CmdArgParser.go, internal/cinfo/CmdArgParser.go, internal/cinfo/cinfo.go, internal/cqueue/CmdArgParser.go, internal/cqueue/cqueue.go, internal/cwrapper/CmdArgParser.go, internal/util/err.go
为除了 cford、calloc、crun 的命令添加错误码
=> Feat: Add error code for commands

internal/cqueue/cqueue.go
=> fix cqueue -o index out of range.

internal/cacct/cacct.go, internal/cqueue/cqueue.go
- fix(cqueue, cacct): multiple whitespaces in format cause error
- fix(cqueue): if `StartTime` is 0, need to show nothing instead of `1970-01-01`
=> Fix some format issues

internal/cacct/CmdArgParser.go, internal/cacct/cacct.go, internal/cqueue/CmdArgParser.go, internal/cqueue/cqueue.go
在 cacct 添加了 state、qos、partition 的 filter，同时修正了 cqueue 中的 state filter。
=> Cacct filter

internal/cacct/CmdArgParser.go, internal/cacct/cacct.go, internal/cacctmgr/CmdArgParser.go, internal/cacctmgr/cacctmgr.go, internal/cqueue/CmdArgParser.go, internal/cqueue/cqueue.go, internal/util/string.go, internal/util/table.go, internal/util/util.go
feat: Add table cell trimming for cacct
feat: Add table cell trimming for cacctmgr
=> feat: Add table cell trimming for cqueue

internal/cacctmgr/cacctmgr.go, internal/util/table.go
Fix: ALLOWEDQOSLIST Displays problems with using ellipsis when the list is too long for cacctmgr
=> Fix: ALLOWEDQOSLIST Displays problems with using ellipsis when the list is too long for cacctmgr

internal/calloc/calloc.go, internal/cbatch/cbatch.go, internal/crun/crun.go, internal/cwrapper/lsf.go, internal/cwrapper/slurm.go
添加申请 CPU 等资源限制，并修复 cwrapper 提交任务时 flag 未修改。
测试文档相关问题：166，170，171，173，174。
=> Bugfix: cwrapper flag not changed

internal/cqueue/cqueue.go, internal/cwrapper/lsf.go
=> fix: Fix bug in cqueue output and LSF wrapper

internal/cwrapper/slurm.go
Fix slurm wrapper cannot identify:
- scontrol update job
- sacctmgr show ...
=> Fix: Update sacctmgr and fix bugs in scontrol wrappers

internal/ccancel/ccancel.go, internal/ccontrol/CmdArgParser.go, internal/ccontrol/ccontrol.go, internal/util/string.go, protos/Crane.proto
`ccontrol update` can submit multiple tasks/nodes at a time
Related PR: PKUHPC/CraneSched#311
=> Feat(ccontrol): Batch update

internal/ccancel/ccancel.go
=> fix ccancel not support multi status

internal/cacct/cacct.go, internal/ccancel/CmdArgParser.go, internal/ccancel/ccancel.go, internal/cqueue/cqueue.go, internal/util/string.go
统合了 cacct, cqueue, ccancel 关于 TaskStatus 的筛选，规范了 ccancel log 输出。
=> refactor state filter

internal/ccontrol/ccontrol.go
=> Update ccontrol.go typo

internal/cacctmgr/cacctmgr.go
=> feat: Add display of coordinator field

internal/cacct/cacct.go, internal/ccancel/ccancel.go, internal/ccontrol/ccontrol.go, internal/cqueue/cqueue.go, internal/cwrapper/slurm.go, internal/util/string.go
=> Refactor param parsing and fix squeue output format

internal/util/util.go
=> Change the length range of the job name

internal/cacctmgr/CmdArgParser.go
=> fix: Optimize modify account/user command.

cmd/ceff/ceff.go, internal/ceff/CmdArgPaser.go, internal/ceff/ceff.go, internal/cplugind/loader.go, internal/util/grpc.go, internal/util/string.go, internal/util/util.go, protos/Crane.proto
功能测试报告：https://e26ruh1viz.feishu.cn/wiki/OZOJwAU5bixCd0kO8jgc9RPLn8b
=> feat: Add command `ceff` for performance info display 

internal/util/version.go
=> feat: version show CraneSched v1.0.0 release

internal/ccontrol/ccontrol.go
=> fix ccontrol show job NodeList output
